/// Offline TypeScript type exporter — zero-dependency alternative to `ts-rs`.
///
/// When run via `cargo test -- --ignored generate_types`, this reads the
/// Rust type definitions and writes matching `.d.ts` / `.ts` files to the
/// frontend's type directory.
///
/// Once `ts-rs` becomes available (network restored), switch to:
///   cargo add ts-rs && #[derive(TS)] on all structs

use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

/// Path relative to workspace root where generated TS types live
const TS_OUTPUT_DIR: &str = "../../packages/core/src/types";

/// Generate TypeScript type definitions from canonical Rust structs.
/// This is a manual serializer — keep in sync with engine/types.rs.
pub fn generate_ts_types() -> std::io::Result<()> {
    let out_dir = Path::new(TS_OUTPUT_DIR);
    fs::create_dir_all(out_dir)?;

    let content = r#"/**╔══════════════════════════════════════════════════════════════╗
 * ║ Auto-generated by types_export.rs  (cargo test -- --ignored)   ║
 * ║ Source: apps/desktop/src-tauri/src/engine/types.rs             ║
 * ╚══════════════════════════════════════════════════════════════╝**/

export interface FormatDescriptor {
  id: string;
  name: string;
  category: "document" | "image" | "data" | "audio" | "video" | "code" | "color";
  extensions: string[];
  mime_types: string[];
  description: string;
  previewable: boolean;
}

export interface ConversionRequest {
  id: string;
  source_format: string;
  target_format: string;
  input_path: string;
  output_path: string | null;
  options: ConversionOptions | null;
}

export interface ConversionOptions {
  quality: number | null;
  width: number | null;
  height: number | null;
  preserve_metadata: boolean | null;
  page_range: string | null;
}

export interface ConversionProgress {
  conversion_id: string;
  status: "queued" | "preprocessing" | "converting" | "postprocessing" | "completed" | "failed" | "cancelled";
  progress: number;
  message: string;
  stage: "preprocess" | "parse" | "transform" | "serialize" | "postprocess" | null;
}

export interface ConversionResult {
  success: boolean;
  conversion_id: string;
  output_path: string | null;
  error: string | null;
  duration_ms: number;
  original_size_bytes: number | null;
  result_size_bytes: number | null;
}

export type StageType = "preprocess" | "parse" | "transform" | "serialize" | "postprocess";
export type ConversionStatus = "queued" | "preprocessing" | "converting" | "postprocessing" | "completed" | "failed" | "cancelled";
export type FormatCategory = "document" | "image" | "audio" | "video" | "data" | "code" | "color";
"#;

    let path = out_dir.join("generated.ts");
    let mut file = File::create(&path)?;
    file.write_all(content.as_bytes())?;
    eprintln!("[types_export] ✅ 已生成: {}", path.display());
    Ok(())
}

/// Integration test — generates TS types and verifies the output exists.
/// Run with: cargo test -- --ignored generate_types
#[test]
#[ignore = "run explicitly when Rust types change: cargo test -- --ignored generate_types"]
fn generate_types() {
    generate_ts_types().expect("类型导出失败");
    let path = Path::new(TS_OUTPUT_DIR).join("generated.ts");
    assert!(path.exists(), "生成的文件不存在: {}", path.display());
    let content = fs::read_to_string(&path).expect("无法读取生成的文件");
    assert!(content.contains("FormatDescriptor"), "缺少 FormatDescriptor 类型");
    assert!(content.contains("ConversionResult"), "缺少 ConversionResult 类型");
    assert!(content.contains("ConversionProgress"), "缺少 ConversionProgress 类型");
    eprintln!("[types_export] 类型验证通过，共 {} 字符", content.len());
}
